### ISSUE TITLE
Request: your skin in the Dracula theme colours?

### ISSUE THREAD

**Issue by dmt-hub** [smoralis/DarkX#1]
Hi,
Thanks for your great skin!
Would be great to have this in the Dracula theme colours. ( https://draculatheme.com/ ) 
<img width="518" alt="Screenshot 2024-08-25 at 18 59 34" src="https://github.com/user-attachments/assets/ca3cc2a6-cc5e-4402-94e3-ea31239ac594">
https://github.com/dracula/dracula-theme/blob/main/README.md

All the best!

**Comment by smoralis** [comment]
It could be done.

Can you provide a mockup showing each elements desired colour ?

**Comment by dmt-hub** [comment]
<img width="446" alt="Screenshot 2024-08-26 at 08 29 44" src="https://github.com/user-attachments/assets/23bf5539-8fc9-4775-971a-e01f3212694b">
It would be like the colors you see in this screenshot.
The background of foobar2000 like in the screenshot.
The basic fonts in this light purple.
other text optoins have the pink & yellow like in the screenshot.
Those would be the basic colors used.

**Comment by smoralis** [comment]
Ok!
What about the seekbar and the buttons?
Any specific colours used?
They not really define the usage in their specs.

**Comment by dmt-hub** [comment]
seekbar could be this color 
<img width="23" alt="Screenshot 2024-08-26 at 08 38 12" src="https://github.com/user-attachments/assets/2b087216-cc1c-4698-ad86-075e91b63e4e"> 
or this
<img width="21" alt="Screenshot 2024-08-26 at 08 38 36" src="https://github.com/user-attachments/assets/3aad06a5-59c0-4366-95d4-36cd7c005e0e">

buttons could be this
<img width="22" alt="Screenshot 2024-08-26 at 08 39 05" src="https://github.com/user-attachments/assets/4bb0ad64-15c2-4e1a-88f2-ed25dc97a283"> or this 
<img width="21" alt="Screenshot 2024-08-26 at 08 39 27" src="https://github.com/user-attachments/assets/38d6d98c-e5ec-403f-885a-0f103e2c438a">
or this
<img width="16" alt="Screenshot 2024-08-26 at 08 39 44" src="https://github.com/user-attachments/assets/56a59e2a-3498-46cf-b1c3-1c6f068eaa3d">

depends on personal preference ofcourse, but any of these colors would be looking good.

**Comment by dmt-hub** [comment]
seekbar in one of those colors would even look better
<img width="30" alt="Screenshot 2024-08-26 at 08 41 44" src="https://github.com/user-attachments/assets/598c3e7f-fd0a-4e41-8117-b9c3d16da95c">

**Comment by smoralis** [comment]
Ok, give me a few days and I will look into it

**Comment by dmt-hub** [comment]
Thats great news! Thanks alot @smoralis !

**Comment by smoralis** [comment]
Done !!
Hope you like it.

https://github.com/smoralis/DarkX-Dracula
https://github.com/smoralis/DarkX-Dracula/releases/download/v1.0.5/DarkX-Dracula.fbskin

**Comment by dmt-hub** [comment]
Thats looking great! thanks alot for your work!!

If i could request a little change - i would not have any opacity on the slider button - 
and use this exact pink & yellow (for the loop buttons etc... and play pause etc.. buttons) -> 
![28731](https://github.com/user-attachments/assets/aac2f9a2-2431-4e79-86e4-a0e5908aded7)

<img width="32" alt="Screenshot 2024-08-27 at 21 28 12" src="https://github.com/user-attachments/assets/0d05ed60-83e7-490c-ac87-3560118405cc">
<img width="127" alt="Screenshot 2024-08-27 at 21 29 28" src="https://github.com/user-attachments/assets/5ec4dbef-a2e4-4d91-8d94-1a04ae546471">
<img width="168" alt="Screenshot 2024-08-27 at 21 29 39" src="https://github.com/user-attachments/assets/f23b0c9a-305c-4067-80fa-0e4573a1e099">

Thanks again!!

**Comment by smoralis** [comment]
My bad, Somewhere I mixed up my RGB's ...

Fixed !

https://github.com/smoralis/DarkX-Dracula/releases/download/v1.0.5a/DarkX-Dracula.fbskin

**Comment by smoralis** [comment]
If you didn't  delete the previous skin in the app it should be listed as DarkX-Dracula (1)

**Comment by dmt-hub** [comment]
Ok, its working now! Perfect, thanks alot!!

**Comment by dmt-hub** [comment]
Could there maybe be an alternative dracula version where the grey seekbar is yellow and all the buttons (play/loop/etc..) also yellow? 🙏
<img width="32" alt="Screenshot 2024-08-28 at 11 20 35" src="https://github.com/user-attachments/assets/80704d97-eced-479c-9640-2c432283f486">

<img width="243" alt="Screenshot 2024-08-28 at 11 19 43" src="https://github.com/user-attachments/assets/848ba9d9-6631-4f29-ba97-c3a6ac9857d5">

**Comment by smoralis** [comment]
The buttons are Orange 255 184 108  , do they show up as white ?
I'm confused with your screenshot.
![68747470733a2f2f64726163756c617468656d652e636f6d2f696d616765732f636f6c6f722d626f7865732f6f72616e67652e706e67](https://github.com/user-attachments/assets/29e858e7-d638-4c24-9742-4d7381bb1321)

![image](https://github.com/user-attachments/assets/606c21f3-0a03-4d5d-8051-18d52a4432af)



Do you want them yellow ?
![68747470733a2f2f64726163756c617468656d652e636f6d2f696d616765732f636f6c6f722d626f7865732f79656c6c6f772e706e67](https://github.com/user-attachments/assets/39cfd18e-d27b-4101-9bac-9cd743297ce1)

**Comment by dmt-hub** [comment]
indeed, they do show up as white here.
this color in your screenshot is perfect!

**Comment by smoralis** [comment]
Try from Settings > Advanced > TWEAKS > CLEAR button (image cache)

**Comment by dmt-hub** [comment]
<img width="499" alt="Screenshot 2024-08-28 at 11 51 55" src="https://github.com/user-attachments/assets/1265d155-1639-4802-a52e-454c62e70006">
Yes that did the trick! looks like expected now!

**Comment by dmt-hub** [comment]
something minimalistic like this style would be great for dracula theme version ->
<img width="339" alt="Screenshot 2024-08-28 at 11 56 13" src="https://github.com/user-attachments/assets/33f2e470-395f-4389-8dc7-1d9ac7812d7b">

**Comment by smoralis** [comment]
If you could match the icons with the available ones in the https://phosphoricons.com/ pack it could be done.

Relative info.
https://hydrogenaud.io/index.php/topic,125529.0.html

**Comment by smoralis** [comment]
What colour do you believe the icons should be?
Orange or something else.?
The below Orange is not  255 184 108.. it is just for reference 

![Screenshot_2024-08-28-19-31-29-327_com foobar2000 foobar2000](https://github.com/user-attachments/assets/1d60c2ec-17d8-48b5-9715-108432eaed11)

**Comment by dmt-hub** [comment]
@smoralis Thats looking really good! 
Again -> thanks alot!! 🙏 
Yes in orange is perfect! 
or to keep it in line w/ dracula theme 255 184 108.

🙏

**Comment by smoralis** [comment]
Menu icons done!

https://github.com/smoralis/DarkX-Dracula/releases/download/v1.0.5b/DarkX-Dracula.fbskin

**Comment by dmt-hub** [comment]
@smoralis The skin is perfect now! Thank you for your time & work!!
🙏🤝👍

**Comment by smoralis** [comment]
Thanks!!
I will close the issue here.
If required create a new issue in the DarkX-Dracula skins repo.
